[package]
name = "deno_audio"
version = "0.1.0"
authors = ["divy-work <dj.srivastava23@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
rodio = "0.12.0"
deno_bindgen = "0.5.0"
