[package]
name = "deno_audio"
version = "0.1.0"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
rodio = "0.17.1"
deno_bindgen = "0.8.1"
